### ISSUE TITLE
Error after changing code locally

### ISSUE THREAD

**Issue by cmthomps** [martijnbastiaan/taiga-contrib-ldap-auth#4]
The fallback option is really handy, so I very much appreciate your work.  I just tried to change the code locally on my taiga box to implement your changes and got the following error.  Any thoughts or guidance?

`ERROR:2017-04-27 13:40:38,043: Internal Server Error: /api/v1/auth
Traceback (most recent call last):
  File "/home/administrator/.virtualenvs/taiga/lib/python3.5/site-packages/taiga_contrib_ldap_auth/services.py", line 69, in ldap_login_func
    username, email, full_name = connector.login(login = login_input, password = password_input)
TypeError: login() got an unexpected keyword argument 'login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/administrator/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/administrator/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/administrator/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/administrator/taiga-back/taiga/auth/api.py", line 145, in create
    data = auth_plugins[login_type]['login_func'](request)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.5/site-packages/taiga_contrib_ldap_auth/services.py", line 70, in ldap_login_func
    except connector.LDAPUserLoginError as ldap_error:
AttributeError: module 'taiga_contrib_ldap_auth.connector' has no attribute 'LDAPUserLoginError'`

**Comment by cmthomps** [comment]
I figured it out, I had to update the connector.py file as well.  It's still not working for me, but I'm not getting the error anymore.

**Comment by martijnbastiaan** [comment]
Yes, the best thing you can do is just clone this whole repository :). Maybe you can add debug statements to the various stages the code goes through and see if it behaves as you expect? I'm willing to help if you provide some more info.

**Comment by cmthomps** [comment]
Thanks so much for responding and offering to help.  I'm going to clone my production virtual machine so I have something to play with without interrupting users.

**Comment by cmthomps** [comment]
I've got an environment to play around on now.  Here's what I did.  I cloned this repository and then copied it into .virtualenvs/taiga/lib/python3.5/site-packages/taiga_contrib_ldap_auth.  I know enough about python to be dangerous, so that may or may not be the right way to do this.

At any rate, as of the moment, I can login with non-ldap users.   If I try an ldap user it fails.  Using PostMan against the API, the error I get back is:

{
  "error_message": {
    "normal": "Username or password does not matches user.",
    "ldap": "LDAP login not found"
  }
}

I didn't change anything with the LDAP configuration.  I can use the same user with the original version of the ldap plugin and it works.

**Comment by cmthomps** [comment]
I got it.  The setting names in taiga-back\settings\local.py have slightly different names.

#LDAP_EMAIL_PROPERTY = 'mail'
#LDAP_FULL_NAME_PROPERTY = 'name'
#LDAP_SEARCH_PROPERTY = 'sAMAccountName'

LDAP_USERNAME_ATTRIBUTE= 'sAMAccountName'
LDAP_EMAIL_ATTRIBUTE = 'mail'
LDAP_FULL_NAME_ATTRIBUTE = 'name'

Thanks for your contribution.
